### ISSUE TITLE
Documentation link invalid

### ISSUE THREAD

**Issue by Yuri05** [systemspharmacology/systemspharmacology.github.io#1]
Documentation link http://docs.open-systems-pharmacology.org/ is not valid

Should redirect to https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation

**Comment by msevestre** [comment]
redirect to documentation or to the pdf download?

**Comment by Yuri05** [comment]
to documentation. It contains >1 pdfs for download already now, so I would just point to the repo's start page

**Comment by msevestre** [comment]
done
