### ISSUE TITLE
Tutorials/Workshops

### ISSUE THREAD

**Issue by Yuri05** [systemspharmacology/systemspharmacology.github.io#10]
In Tutorials section, add 2 hands-on exercises on the web-page, so people know that this is not only videos
(select any 2 from [the list](https://github.com/Open-Systems-Pharmacology?utf8=%E2%9C%93&q=%22workshop%22&type=&language=) e.g. PAGE and Acop)

**Comment by msevestre** [comment]
nothing on the PAGE website. 
Also we need descirption for the different exercies

**Comment by msevestre** [comment]
@Yuri05 @TheiBa
I have updated the tutorial section
https://systemspharmacology.github.io/#tutorials

We need a slightly longer description for the new hands on exercises. I took the description out of #6 but I think this is just too short right now. Thoughts

**Comment by TheiBa** [comment]
Proposal
PBPK MODEL BUILDING
Building a simple PBPK model of ciprofloxacin: learn how to optimize parameters based on PK and mass balance information after intravenous and oral administration

PK age-dependence
Simulating the PK of morphine in children and older adults: learn how PBPK models can be used to assess how physiological changes in body composition and ADME protein activity quantitatively impact the PK in different age groups

**Comment by msevestre** [comment]
done
