### ISSUE TITLE
Examples section

### ISSUE THREAD

**Issue by Yuri05** [systemspharmacology/systemspharmacology.github.io#11]
Examples section on website:
* rename “Exampels” to “Example models”  
* add link to [GIM](https://github.com/Open-Systems-Pharmacology/Glucose-Insulin-Model) 
  * Name: **Glucose Insulin Model**
  * Description: _Scientifically exciting for diabetes researchers. Technically exciting for everyone with PBPK models of glucose, insulin, and glucagon coupled through non-mechanistic PD as well as systems pharmacology PD models._
* delete (comment out) other examples for now; we can re-introduce them when we get descriptions

**Comment by msevestre** [comment]
@Yuri05 @TheiBa
Renaming Example to Example models? We should try to keep the menu entries as short as possible as we already have a lot
What other example can we have beside models?

**Comment by msevestre** [comment]
done aside from rename

**Comment by TheiBa** [comment]
Well, for me, these are primary (substance) models, and example model was a 
compromise. Examples could be on coding or processes, such as taking an 
existing model and doing something with it, like simulating, extrapolating, 
analyzing whatever?
