### ISSUE TITLE
OSP-based-publications-and-content

### ISSUE THREAD

**Issue by TheiBa** [systemspharmacology/systemspharmacology.github.io#16]
Thinking about
https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content

I think we already have (at least) 3 categories there:
- classical journal publications (some may also be tutorial like), no unified label yet, but I could easily apply that to ~100 entries
- hands-on exercises
- video tututorials 

I think we should add one issue for each osp-model repo, i.e. for models that have been published on OSP. Actually, the label and a first example is already there, I  just notice. And the hands-on exercises in theory also include osp-models. 

And then refine the ReadMe under above link accordingly, listing the four categories. Additional categories that have been started: Presentations, which could be further divided into slides and posters.

**Comment by msevestre** [comment]
Is there anything to do for the website here?

**Comment by TheiBa** [comment]
I updated/structured the readme. On the homepage, under models I would prefer to link to
https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3Aosp-model
where we still need individual issues for 
https://github.com/Open-Systems-Pharmacology?q=%22osp-model%22
then

Journal publications 
https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/issues?q=is%3Aopen+is%3Aissue+label%3AJournal
Growing list of scientific journal publications that relates to OSP or describes work with PK-Sim or MoBi. Add your own contributions and label them or others appropriately to further grow and structure this database.

**Comment by msevestre** [comment]
website updated

**Comment by TheiBa** [comment]
The picture I sent was not suitable? 
<https://github.com/notifications/beacon/AYQo2a5xaP87grEioREr0mFfMsf6cp_4ks5slCdfgaJpZM4PctY3.gif>
