### ISSUE TITLE
new screenshot

### ISSUE THREAD

**Issue by Yuri05** [systemspharmacology/systemspharmacology.github.io#17]
Need new screenshot in the News&Releases-section.
The current one is blurry and contains a mouse pointer

**Comment by msevestre** [comment]
yep

**Comment by msevestre** [comment]
I think best would be if you guys take the screenshot and then I ask the designer to cut it and format it somehow (round corner whatever)

Please use the standard FONT SIZE and SKIN

**Comment by msevestre** [comment]
/cc @TheiBa 
You mentioned a few projects in the past...

**Comment by Yuri05** [comment]
>Please use the standard FONT SIZE and SKIN

Ok, not my case then :-) @TheiBa: can you do this?

**Comment by TheiBa** [comment]
What do you need - PK-Sim or MoBi, both? Cannot me mentioning something in that context in the pas though ...

**Comment by msevestre** [comment]
RIght now we show one screenshot in the design so I only need one. It could be MobI, or PKSim or both at the same time.  
At most it will be this size http://localhost:4000/img/news_pic.png so it needs to be small
