### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by Yuri05** [systemspharmacology/systemspharmacology.github.io#18]
I would add a link to Donato's tutorial: [this](https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/issues/97) or directly [this](http://onlinelibrary.wiley.com/doi/10.1002/psp4.12134/abstract)

If the section becomes too big (too many tutorials): Remove e.g. _Favorites in PK-Sim® and MoBi®_ video tutorial

**Comment by msevestre** [comment]
Sure. What's the title and short description?

**Comment by msevestre** [comment]
well i guess it's written here somehow
https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/issues/97

**Comment by Yuri05** [comment]
yes, would take it from there.

Title: **How to Build a PBPK/PD Model.**
Description: **Introduce the fundamental concepts of physiologically based pharmacokinetic/pharmacodynamic (PBPK/PD) modeling with a special focus on their practical implementation in a typical PBPK model building workflow.**

**Comment by msevestre** [comment]
done
