### ISSUE TITLE
Contribution section

### ISSUE THREAD

**Issue by Yuri05** [systemspharmacology/systemspharmacology.github.io#2]
I think we also need a section "Contribution". Here the statement "Contributions are welcome bla bla"should be placed and also the most impartant linksto:
o   Contribution guidelines
o   Coding standards
o   Getting started
o   Git-Wokflow

Currently some of those links are just displayed at the very bottom of the page - not enough for me

**Comment by msevestre** [comment]
I kind of disagree with that. The website is not intended for developers. Rather this will be the front end for modellers and scientists

**Comment by Yuri05** [comment]
Also modellers/scientists can contribute (models, examples, algorithm improvements, sharing their articles/tutorials, scientific discussions etc. etc.). 
I think it's really important

**Comment by Yuri05** [comment]
So I would at least write in the Contribution-Section what is already written in the ["Ways to contribute"-paragraph](https://github.com/Open-Systems-Pharmacology/Suite/blob/master/CONTRIBUTING.md#ways-to-contribute) in CONTRIBUTING.md and put the link to contributing.md.

**Comment by msevestre** [comment]
Looking forward to the first contribution then ;-)

**Comment by msevestre** [comment]
We don't need that anymore do we?

**Comment by Yuri05** [comment]
Yep. closing
