### ISSUE TITLE
Which icon for video tutorial

### ISSUE THREAD

**Issue by msevestre** [systemspharmacology/systemspharmacology.github.io#20]
![image](https://user-images.githubusercontent.com/1041237/30697184-125d8dc4-9eac-11e7-8001-213a8be3f5e3.png)

Either the arrow or the movie?

I have used a text file for stuff to read

or any other suggestion ?

http://fontawesome.io/icons/

**Comment by Yuri05** [comment]
Movie-Icon

**Comment by msevestre** [comment]
done
