### ISSUE TITLE
extend opening header

### ISSUE THREAD

**Issue by TheiBa** [systemspharmacology/systemspharmacology.github.io#5]
with PK-Sim® and MoBi® for Quantitative Systems Pharmacology
-> with PK-Sim® and MoBi® for PBPK and Quantitative Systems Pharmacology
or
-> with PK-Sim® and MoBi® for Quantitative Systems Pharmacology including PBPK
or ...

**Comment by msevestre** [comment]
That's the text from our readme . Nothing new here

**Comment by TheiBa** [comment]
OK, see where it comes from. Nevertheless, it does not solve the issue I 
addressed. I would recommend updating the readme accordingly.

**Comment by msevestre** [comment]
yeah but I need a clear final decision. 
which one is it ? (to me the last one does not sound right but again, I have no idea)

**Comment by TheiBa** [comment]
ok, just discussing with Rolf: why not directly use the vision and mission 1to1

Vision & Mission of Open Systems Pharmacology

Vision

Robust and reliable, easy-to-use modeling & simulation tools, processes and models for pharmaceutical and other life-sciences applications qualified and accepted by a scientific community from academia, regulatory agencies and industry available and open to everyone.

Mission

Provide a platform for joint development, review & qualification, and application of state-of-the-art tools for PBPK and Systems Pharmacology modeling and an open library of models for application as well as method & tool qualification purposes. Promote the idea of pre-competitive open collaboration for the advancement of modeling & simulation sciences in pharmaceutical and life science.

**Comment by msevestre** [comment]
This does not read well. When I read this paragraph, it feels that words are missing. Sentences are also too long. 
But whatever, I'll add that to the website and you guys can decide

**Comment by msevestre** [comment]
and I think that somewhere PKSim and MoBi should be visible.

**Comment by msevestre** [comment]
I have updated the website. I think not mentioning PK-Sim and MoBi in the main section is a mistake

**Comment by msevestre** [comment]
Maybe add PKSim and MoBi in the green title? Not great but better than not mentioning it

**Comment by msevestre** [comment]
This is the before
![image](https://user-images.githubusercontent.com/1041237/30335175-38d5d8a0-97a7-11e7-9522-a8450f23bb02.png)


and after
![image](https://user-images.githubusercontent.com/1041237/30335189-43490ece-97a7-11e7-9c1c-da00a0057041.png)


too much text IMO

**Comment by TheiBa** [comment]
My main point was that PBPK should be in, Rolfs main point was to not restrict it to PK-Sim and MoBi and that the Vision and Mission was already aligned. I agree that currently the focus is around PK-Sim and MoBi and models therein, and at least from my point of view that will stay for some time to come. And yes, optically, the 1st/short version is nicer. Anyway, why not “invite” Rolf/Jörg to this repo/issue. My vote, considering above, is “with PK-Sim® and MoBi® for PBPK and Systems Pharmacology” and then the vision text without the mission text, i.e. very close to your original proposal but including PBPK (which is also part of the mission, where even we distinguish PBPK and SP, but not the vision) ;-) Alternatively, we agree for now to, e.g., my proposal, and you present that to Rolörg later on.

**Comment by msevestre** [comment]
I like your proposal as well. +1

**Comment by msevestre** [comment]
I am going to revert that for now until we get something that looks ok and reads well. Long texts in header goes against any core website design conceots

**Comment by TheiBa** [comment]
I think we agreed on “our proposal”? with PK-Sim® and MoBi® for PBPK and Systems Pharmacology

**Comment by msevestre** [comment]
you and I did. But it goes against what I was "told" to do :)

**Comment by TheiBa** [comment]
OK. Why told you else? Anyway, then sort it out with that person or make the 
compromise proposal to that person that we agreed on ;-)

**Comment by msevestre** [comment]
done
