### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by TheiBa** [systemspharmacology/systemspharmacology.github.io#6]
heading: subheading (->link)
PBPK model building: Building a simple PBPK model of ciprofloxacin (-> ISSX Session 2)
PK Drug-Drug-Interaction: Simulating the DDI of rifampicin and midazolam (-> ISSX Session 3)
PK age-dependence: Simulating the PK of morphine in children and older adults (-> ISSX Session 4) 

or just start simple with a link to a recent workshop repo, e.g. from ISSX; this can be extended over time, e.g. in the style outlined; we should either way generate and then keep an overview somewhere, I would propose a project like https://github.com/msevestre/substances/projects to be transferred

**Comment by msevestre** [comment]
aren't those tutorials? 
Examples, as far as I understand the request, are example projects for PKSim or MoBi

**Comment by Yuri05** [comment]
>Examples, as far as I understand the request, are example projects for PKSim or MoBi

Yes, examples are just example projects.

>or just start simple with a link to a recent workshop repo, e.g. from ISSX; this can be extended over time

This is what we have now under **Training Materials** (s. Link in **Essentials**-Section)

>PBPK model building: Building a simple PBPK model of ciprofloxacin (-> ISSX Session 2)
PK Drug-Drug-Interaction: Simulating the DDI of rifampicin and midazolam (-> ISSX Session 3)
PK age-dependence: Simulating the PK of morphine in children and older adults (-> ISSX Session 4)

Those I would suppose to be tutorials?

**Comment by TheiBa** [comment]
These are hands-on exercises from workshops that contain instructions for building example projects as well as solutions, which would from my perspective be example projects then. If we have that as “Training material” also fine and we should not double it. I guess Training material would from my perspective include exercises and tutorials. If looking for content for the website, maybe rather skip the “Examples” section for now and add “Training material” or “Exercises”. Or, well, at least the Glucose-Insulin Model would be a nice example, I guess? Is there more? I think there are quite some things in the pipeline, but I think launching the website should not wait for that to happen, we can always add content as it comes and should have enough to start with. 

 

I guess publication list as well as “planning projects” like the substance library are also good candidates for the homepage once having reached a certain stage. Maybe we add an “experimental” category on the website and put them there to indicate the status nascendi?

**Comment by TheiBa** [comment]
I finally looked what is behind the current examples. Not sure they can be described as exciting as done. I would restrict it to:
"Glucose Insulin Model 
Scientifically exciting for diabetes researchers. Technically exciting for everyone with PBPK models of glucose, insulin, and glucagon coupled through non-mechanistic PD as well as systems pharmacology PD models." 
for now, announcment with more to come referencing to substance library in status nacendii, browse with link/list as is.

**Comment by msevestre** [comment]
@TheiBa Fullly agreed. I think our current examples (aside from GIM) are not even worth mentioning

**Comment by TheiBa** [comment]
I do not see that as a real problem though. As said – there is more in the pipeline, but the webpage is basically ready and should be launched asap. And there is enough to put there. And I really vote for adding the status nascendii category (category being things like Essentials and News & Releases for me). We can agree on the projects to be transferred from your repo and the place to go, and implement for decision. Deleting/commenting it out, in case Rolörg vote for postponement should be trivial.

I vote for projects to be transferred to Vision and Mission

-          Substance library

-          ADME library

-          SpecPop

And to publications:

-          examples from workshops

Although for latter we already have separate repos each and a filter to get the status, thus might not be required.   

For the earlier, there might be other suitable repos to place the project, I would be open and hope for your suggestion. For example, my original though was the publications repo, as I see many overlapping labels. The only argument against would be the mixed issues, but with a “journal” filter one would still get a more classical publication list. We could rename it to “Content and publications” then?

**Comment by msevestre** [comment]
Status nascendii lol. Never heard of that before

**Comment by TheiBa** [comment]
No Latin education eh ;-) But a perfect description!? We should check the Latin spelling/grammar though...mine is rusty

**Comment by msevestre** [comment]
I'd bet that i am not the only one who will have no idea what that means. I'd suggest to use a word that is more widely known

I like the idea of linking to projects instead of (or on top of) repositories

**Comment by TheiBa** [comment]
Work in progress, under construction or development ... my favorite remains "in statu nascendi" ... I think most people with a natural science (less math and IT, sorry) background will know it ...

**Comment by msevestre** [comment]
Well I asked Andrea and she had never heard about it. I think she is a good potential candidate

**Comment by msevestre** [comment]
Work in progress is definitely something that everyone (even Math/IT people) will understand

**Comment by TheiBa** [comment]
Well then ... however, thinking about it, work in progress is basically everything ;-) what about (in the) nascent state? Or other suggestions from the native speaker?

**Comment by Yuri05** [comment]
>Fullly agreed. I think our current examples (aside from GIM) are not even worth mentioning

Disagree. GIM is still the most prominent (and best described) model, but most of another examples (_Paracetamol_, _Theophylline_, _Aciclovir_, _Caffeine_) were used to qualify our GI-model and contain a lot of experimental data from numerous articles. I think this is worth mentioning - we just need to get a good description from Katrin Coboeken.

**Comment by TheiBa** [comment]
OK. I am fine to present these examples, from my perspective best when selecting “browse”, also because the “just” you mention is there but should not prevent us going ahead before we sort that out.

**Comment by TheiBa** [comment]
And examples then is rather what I called "substance library", i.e. models for substances. And the library being in the nascent state - we have some, but there the description should be extended for this purpose. And more is in the pipeline, where we should directly get it right - writing could then just be referencing to the publication where they are described. I guess we could also do that for the ones there are, guess most is based on Thelen 2011 ...

**Comment by msevestre** [comment]
@all: I am not following anymore...sorry 

Would you please open another issue and let me know clearly what should appear on the site? 
Thanks :)

**Comment by TheiBa** [comment]
discussing/deciding with Juri next to me:

-          rename repo “OSP-based-publications” to “publications and content”

-          https://github.com/search?q=topic%3Atraining+org%3AOpen-Systems-Pharmacology <https://github.com/search?q=topic%3Atraining+org%3AOpen-Systems-Pharmacology&type=Repositories> &type=Repositories

o   delete label “training”, add label “tutorial”, “workshop” for repos

-          generate issue in pub-list (i.e. publications and content repo) for each hands-on exercise and link at least one of the workshops, e.g. the most recent ISSX (on the long-run, we will generate repo for each exercise and workshops will “recruit” from there); at PAGE we had additional ones, can add those any time, after checking in more detail; add “tutorial” and “workshop” label to each issue

o   PBPK model building: Building a simple PBPK model of ciprofloxacin (-> ISSX Session 2)

o   PK Drug-Drug-Interaction: Simulating the DDI of rifampicin and midazolam (-> ISSX Session 3)

o   PK age-dependence: Simulating the PK of morphine in children and older adults (-> ISSX Session 4)

-          link in tutorial section than graps all video and written tutorials/hands-on exercises

-          in Essentials section, rename “Training Materials” to Tutorials and link to Tutorial section of the the webpage

-          In Tutorials section, add 2 hands-on exercises on the web-page, so people know that this is not only videos, possibly delete 2 videos, if too long otherwise -> people will get the full list via the “Browse” button

-          https://github.com/Open-Systems-Pharmacology?utf8=%E2%9C%93&q=%22examples%22&type=&language=

o   delete label “example-project”, add label “osp-model”

-          Examples on website:

o   rename “Exampels” to “Example models”  

o   add GIM:

§  Glucose Insulin Model
Scientifically exciting for diabetes researchers. Technically exciting for everyone with PBPK models of glucose, insulin, and glucagon coupled through non-mechanistic PD as well as systems pharmacology PD models."

o   delete (comment out) other examples for now; we can re-introduce them when we get descriptions

**Comment by Yuri05** [comment]
Ok, I renamed the publications repo and changed Repo-Topics for examples, models and workshops as discussed above.

for the rest new issues are created:
#8 
#9 
#10 
#11 

so I will close the issues now
