### ISSUE TITLE
Tutorial-Issues for workshops

### ISSUE THREAD

**Issue by Yuri05** [systemspharmacology/systemspharmacology.github.io#8]
generate issue in [pub-list](https://github.com/Open-Systems-Pharmacology/OSP-based-publications-and-content/issues) (i.e. publications and content repo) for each hands-on exercise and link at least one of the workshops, e.g. the most recent ISSX (on the long-run, we will generate repo for each exercise and workshops will “recruit” from there); at PAGE we had additional ones, can add those any time, after checking in more detail; add “tutorial” and “workshop” label to each issue
* PBPK model building: Building a simple PBPK model of ciprofloxacin (-> ISSX Session 2)
* PK Drug-Drug-Interaction: Simulating the DDI of rifampicin and midazolam (-> ISSX Session 3)
* PK age-dependence: Simulating the PK of morphine in children and older adults (-> ISSX Session 4)

**Comment by Yuri05** [comment]
@TheiBa kann YOU do this?

**Comment by TheiBa** [comment]
sure - about as fast as you creating this issue @Yuri05 ... done

**Comment by Yuri05** [comment]
:rocket:

**Comment by msevestre** [comment]
LOL. you guys are on FIRE
