### ISSUE TITLE
Essential/Training Materials

### ISSUE THREAD

**Issue by Yuri05** [systemspharmacology/systemspharmacology.github.io#9]
in Essentials section, rename “Training Materials” to Tutorials and link to Tutorial section of the the webpage

**Comment by msevestre** [comment]
That I don't get. We already have the menu entries with the Tutorial section.

**Comment by msevestre** [comment]
maybe we remove this section altogether? in the essential I mean. Otherwise this is illogical

**Comment by msevestre** [comment]
Done when I removed the tutorial section in essentials to use the floating menu instead. we can revert if we don't like it
